// <auto-generated />
namespace MobilePhoneStoreEcommerce.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class ModifyOrderTableConstraintUniqueSellerIDCustomerIDOrderTime : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ModifyOrderTableConstraintUniqueSellerIDCustomerIDOrderTime));
        
        string IMigrationMetadata.Id
        {
            get { return "202101200652480_ModifyOrderTableConstraintUniqueSellerIDCustomerIDOrderTime"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
